return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	event = { "BufRead", "BufWritePost" },
	config = function()
		require("nvim-treesitter.configs").setup({
			auto_install = false,
			sync_install = false,
			ignore_install = {},
			modules = {},
			ensure_installed = {
				"bash",
				"c",
				"cmake",
				"cpp",
				"css",
				"diff",
				"dockerfile",
				"fennel",
				"git_rebase",
				"gitattributes",
				"gitcommit",
				"go",
				"gomod",
				"gosum",
				"gowork",
				"hcl",
				"html",
				"http",
				"hurl",
				"javascript",
				"jsdoc",
				"json",
				"jsonc",
				"lua",
				"luap",
				"make",
				"markdown",
				"markdown_inline",
				"norg",
				"proto",
				"python",
				"query",
				"rasi",
				"regex",
				"rust",
				"scss",
				"terraform",
				"toml",
				"tsx",
				"typescript",
				"vim",
				"vimdoc",
				"yaml",
			},
			playground = { enable = true },
			highlight = { enable = true },
			indent = { enable = false },
			autotag = { enable = true },
			matchup = { enable = true },
  })
  end
}
